#!/bin/env python3

from typing import NamedTuple
import subprocess
from typing import Any, Iterator
import json
import sys
import os
import time


class OutputParams(NamedTuple):
    x: int
    y: int
    scale: float


class Rect(NamedTuple):
    w: int
    h: int
    x: int
    y: int

    @classmethod
    def from_xywh(cls, x, y, w, h) -> "Rect":
        return cls(w, h, x, y)

    def to_bbox(self) -> tuple[int, int, int, int]:
        return (
            self.x,
            self.y,
            self.x + self.w,
            self.y + self.h,
        )

    def relative_to_output(
        self, output: OutputParams | None, window: "Rect | None"
    ) -> "Rect":
        if output is None:
            output = OutputParams(x=0, y=0, scale=1)

        if window is None:
            window = Rect(0, 0, 0, 0)

        return Rect(
            round(self.w / output.scale),
            round(self.h / output.scale),
            round(self.x / output.scale + window.x - output.x),
            round(self.y / output.scale + window.y - output.y),
        )

    def __str__(self) -> str:
        return f"{self.w}x{self.h}+{self.x}+{self.y}"


def get_active_windows_rect() -> tuple[OutputParams | None, Rect | None]:
    def walk(
        node: dict[str, Any],
        curr_output_params: OutputParams | None,
    ) -> Iterator[tuple[OutputParams, Rect]]:
        if node.get("type") == "output":
            curr_output_params = OutputParams(
                x=node["rect"]["x"],
                y=node["rect"]["y"],
                scale=node.get("scale", 0),
            )

        sub_nodes = node.get("floating_nodes")
        if sub_nodes:
            for sub_node in sub_nodes:
                yield from walk(sub_node, curr_output_params)

        sub_nodes = node.get("nodes")
        if sub_nodes:
            for sub_node in sub_nodes:
                yield from walk(sub_node, curr_output_params)

        elif node.get("pid") and node.get("focused"):
            rect = node["rect"]
            window_rect = node["window_rect"]
            yield (
                curr_output_params,
                Rect(
                    window_rect["width"] - 1,
                    window_rect["height"] - 1,
                    rect["x"] + window_rect["x"] + 1,
                    rect["y"] + window_rect["y"] + 1,
                ),
            )

    process = subprocess.run(
        ["swaymsg", "-t", "get_tree"],
        capture_output=True,
        check=True,
    )
    tree = json.loads(process.stdout.decode())
    return next(walk(tree, None), (None, None))


def run():
    import pyscreenshot
    import cv2 as cv
    import numpy as np

    output_params, active_win_rect = get_active_windows_rect()
    if active_win_rect is None:
        print("No active window found. Quitting.", file=sys.stderr)
        return

    pil_img = pyscreenshot.grab(active_win_rect.to_bbox())
    img = cv.cvtColor(np.array(pil_img), cv.COLOR_BGR2GRAY)

    edges = cv.Canny(img, 70, 220)
    kernel = np.ones(
        (round(2.5 * output_params.scale), round(4.5 * output_params.scale)), np.uint8
    )
    dilated_edges = cv.dilate(edges, kernel)
    contours, _ = cv.findContours(dilated_edges, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)

    rects = []
    small_rects = []

    for contour in contours:
        rect = Rect.from_xywh(*cv.boundingRect(contour)).relative_to_output(
            output_params, active_win_rect
        )
        if rect.h >= 50 or rect.w >= 500 or rect.h <= 3 or rect.w <= 7:
            continue

        if rect.h < 7:
            small_rects.append(rect)
        else:
            rects.append(rect)

    small_rects.sort(key=lambda rect: rect.y)
    curr_rect = None
    for i in range(1, len(small_rects)):
        prev_rect = small_rects[i - 1]
        curr_rect = small_rects[i]

        if (
            curr_rect.y - prev_rect.y - prev_rect.h < 10
            and abs(curr_rect.x - prev_rect.x) < 10
        ):
            small_rects[i] = Rect(
                w=curr_rect.w + curr_rect.x - prev_rect.x,
                h=curr_rect.h + curr_rect.y - prev_rect.y,
                x=prev_rect.x,
                y=prev_rect.y,
            )
        else:
            rects.append(prev_rect)
    if curr_rect is not None:
        rects.append(curr_rect)

    rects.sort(key=lambda rect: -rect.h * rect.w)

    process = subprocess.run(
        ["wl-kbptr", "-o", "general.modes=floating,bisect"],
        input="\n".join(map(str, rects)).encode(),
        check=False,
    )


def get_namedpipe_path() -> str:
    run_dir = os.getenv("XDG_RUNTIME_DIR", "/tmp")
    wayland_display = os.getenv("WAYLAND_DISPLAY", "wayland-0")
    return f"{run_dir}/wl-kbptr-hints-{wayland_display}"


def run_loop(pipe_path):
    try:
        os.mkfifo(pipe_path)
        run()
        while True:
            with open(pipe_path) as pipe:
                while line := pipe.readline():
                    match line.strip():
                        case "run":
                            run()
                        case "quit":
                            return
    finally:
        os.unlink(pipe_path)


def main():
    pipe_path = get_namedpipe_path()
    running = False
    try:
        os.stat(pipe_path)
        running = True
    except:
        pass

    if running:
        print("Already running. Sending 'run' message.", file=sys.stderr)
        with open(pipe_path, "a") as pipe:
            pipe.write("run\n")

    else:
        run_loop(pipe_path)


if __name__ == "__main__":
    main()
